# This file was generated by GoReleaser. DO NOT EDIT.
cask "gofollower" do
  version "1.20260727182345"

  on_macos do
    on_intel do
      sha256 "e4cb2642ac7daa88582c0ba54e762a28e536a92c2a73f8ac161df5efa4b00d92"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "404754c17f94d3a78e56af11f2e84ca5823cfdab9b44bb3321fb2b8ec1625a6e"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ebf7b4caa30387d0b63229f12f551cfa8db3f1e8a1f9b9ad46ff4f13f65da77"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a3c0f0dcd49d3847c43c191f236f55f23b8e3b4d0a441f26de905ac9036ca76"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gofollower"
  desc "Command-line utility for following HTTP links"
  homepage "https://github.com/jksolbakken/gofollower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "follow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/follow"]
    end
  end

  # No zap stanza required

end
