# This file was generated by GoReleaser. DO NOT EDIT.
cask "gofollower" do
  version "1.20260616173338"

  on_macos do
    on_intel do
      sha256 "578eb8c595627b1dfc86ae7759a2e32f2de474900736cd48393ae3ec9ccec1e5"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cbc84f7ed74075f5538ddd32121d2a483fa5922037f20cce7d909817461dc34b"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41055ab3bded80ab21864bb55d4c70ce3a24a7300d4ca1c276963fa6ce3cd3ae"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a798b505e7c244faf5cc33c0961a8ac2a68c8e3662795c15ceeb448a302566f3"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gofollower"
  desc "Command-line utility for following HTTP links"
  homepage "https://github.com/jksolbakken/gofollower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "follow"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/follow"]
    end
  end

  # No zap stanza required

end
