# This file was generated by GoReleaser. DO NOT EDIT.
cask "gofollower" do
  version "1.20260508183914"

  on_macos do
    on_intel do
      sha256 "f7dc714b9f10e3c9a2bc4731ff4bd74b33059d4ae241dbdbe097498127e6bbb3"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "aae918ebb43591060163f86abbaafa1ef25acf5814c10a3923bf5ce3025c0f84"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99a18d90a4f1867c3d606afa7a14dfb663d37403c886581af81a918bec957362"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8acb07a5e634c2bafb8f84faf1d2cd1a0a583e894e3c886089df2649bfbdd54a"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gofollower"
  desc "Command-line utility for following HTTP links"
  homepage "https://github.com/jksolbakken/gofollower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "follow"

  # No zap stanza required

end
