# This file was generated by GoReleaser. DO NOT EDIT.
cask "gradleconf" do
  version "1.20260922153753"

  on_macos do
    on_arm do
      sha256 "e22da824d208694d0f9ee1625f85437b26dff9fd5a9223b8d3b2bb2b4130dcde"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3288f535036eef0cd64f39d4c82b0a2e6091156d19291aca2643be2e4133f919"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7b86fd5ae6b63904d5751441e62bb96caa40a4fa8e6abdf31cd9cc25b1d0cdf3"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bcfe9b0531d3bfdb47652e557415e3f1bd6b6753b919553527494cdd994221e2"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gradleconf"
  desc "Opinionated tool for configuring single module Kotlin Gradle projects"
  homepage "https://github.com/jksolbakken/gradleconf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gradleconf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gradleconf"]
    end
  end

  # No zap stanza required
end
