# This file was generated by GoReleaser. DO NOT EDIT.
cask "gradleconf" do
  version "1.20260509082920"

  on_macos do
    on_intel do
      sha256 "f1ae73bdcc5badab810e153a13be0116e092bdea24eb9a78d5ee21195be361a8"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c69ea3db66981cda3ffff7c637b7dfe03f5ec7a7b52e741ecc5221f63e91cd47"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7bbc95346899f1600c6ce89fdd05e056e343046cfdbebd763101ab5b1c0cd7e6"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "796f9e0702351dc9b0238004e67744712b015a51c6a834f8d3512c53c32812ac"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gradleconf"
  desc "Opinionated tool for configuring single module Kotlin Gradle projects"
  homepage "https://github.com/jksolbakken/gradleconf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gradleconf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gradleconf"]
    end
  end

  # No zap stanza required

end
