# This file was generated by GoReleaser. DO NOT EDIT.
cask "gradleconf" do
  version "1.20260616173413"

  on_macos do
    on_intel do
      sha256 "4f8d01ad321ea48588367acc1aa6abc050f1267ec8b748fc9ce0d1b6b9934815"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf8e3d34db309f5f6af0465d44afb66cd39bca8ca9580040e3573ed00de9f8c3"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4082624ba3be66f7b5a8588aac6a4fe622422c4270e160b9673ad54c9d860a44"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a00fa03f3793bac5c83552fcf5520cec13d628563cf96be4fbc1481a96d50232"
      url "https://github.com/jksolbakken/gradleconf/releases/download/#{version}/gradleconf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gradleconf"
  desc "Opinionated tool for configuring single module Kotlin Gradle projects"
  homepage "https://github.com/jksolbakken/gradleconf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gradleconf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gradleconf"]
    end
  end

  # No zap stanza required

end
