# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gofollower < Formula
  desc "Command-line utility for following HTTP links"
  homepage "https://github.com/jksolbakken/gofollower"
  version "1.20251005185910"

  on_macos do
    on_intel do
      url "https://github.com/jksolbakken/gofollower/releases/download/1.20251005185910/gofollower_1.20251005185910_darwin_amd64.tar.gz"
      sha256 "86b48f5a4174ac0e6280e0cc49d33ac452c0cb150c0f7f376bf97a8855d9906b"

      def install
        bin.install "follow"
      end
    end
    on_arm do
      url "https://github.com/jksolbakken/gofollower/releases/download/1.20251005185910/gofollower_1.20251005185910_darwin_arm64.tar.gz"
      sha256 "3de00171176e415292103da2398af83e5d6fc5ae1ec942f00d8f8ddeea3363c2"

      def install
        bin.install "follow"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jksolbakken/gofollower/releases/download/1.20251005185910/gofollower_1.20251005185910_linux_amd64.tar.gz"
        sha256 "aacff6a81d7d29f542ae2f32293f9b0c63145ddef30cfbed063e02756159249e"

        def install
          bin.install "follow"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jksolbakken/gofollower/releases/download/1.20251005185910/gofollower_1.20251005185910_linux_arm64.tar.gz"
        sha256 "21cb3c462cbd70fff4057deb349cbe8a156f95ce7991facd5237258e25e20ab6"

        def install
          bin.install "follow"
        end
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/follow version")
  end
end
