# This file was generated by GoReleaser. DO NOT EDIT.
cask "gofollower" do
  version "1.20260508182405"

  on_macos do
    on_intel do
      sha256 "43944d2afa676fb1426865b432b4467d3b5e1bb078c56172be6a739c55c73192"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cb694ee1fae3c7d5eefd0965f68746f1a7f98cde46ce6ce3b0335bcab4dbd7cc"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "56480e759e975c77481cf3c4b9477e558263f504edaad7a95ff8bf1ec2283a8f"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "792516bb0915c8c3dcb61ac48a2c12cfb8bd7de3a097b377a0e0a35fec73cc2d"
      url "https://github.com/jksolbakken/gofollower/releases/download/#{version}/gofollower_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gofollower"
  desc "Command-line utility for following HTTP links"
  homepage "https://github.com/jksolbakken/gofollower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "follow"

  # No zap stanza required

end
