# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gradleconf < Formula
  desc "Opinionated tool for configuring single module Kotlin Gradle projects"
  homepage "https://github.com/jksolbakken/gradleconf"
  version "1.20260103155928"

  on_macos do
    on_intel do
      url "https://github.com/jksolbakken/gradleconf/releases/download/1.20260103155928/gradleconf_1.20260103155928_darwin_amd64.tar.gz"
      sha256 "30aeb2ebbf4c6107842dc2ec9cbf77349fba4e33e713b5758276437b79607eaf"

      def install
        bin.install "gradleconf"
      end
    end
    on_arm do
      url "https://github.com/jksolbakken/gradleconf/releases/download/1.20260103155928/gradleconf_1.20260103155928_darwin_arm64.tar.gz"
      sha256 "98bac12b7f40769fc82894dfe5eed751c9fe64eef83890013b4a03fb412718fa"

      def install
        bin.install "gradleconf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jksolbakken/gradleconf/releases/download/1.20260103155928/gradleconf_1.20260103155928_linux_amd64.tar.gz"
        sha256 "8cd4238dc9acc72882af2cca71a85fac43c40b45d1376c20703040a48e5bc935"

        def install
          bin.install "gradleconf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jksolbakken/gradleconf/releases/download/1.20260103155928/gradleconf_1.20260103155928_linux_arm64.tar.gz"
        sha256 "9c3c46191d8788ae7b865f4f69d5721a3ee33a067cb6cd11283d827411d666c8"

        def install
          bin.install "gradleconf"
        end
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/gradleconf version")
  end
end
