# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gradleconf < Formula
  desc "Opinionated tool for configuring single module Kotlin Gradle projects"
  homepage "https://github.com/jksolbakken/gradleconf"
  version "1.20260331025518"

  on_macos do
    on_intel do
      url "https://github.com/jksolbakken/gradleconf/releases/download/1.20260331025518/gradleconf_1.20260331025518_darwin_amd64.tar.gz"
      sha256 "7a8171e67bd885b6048ac808c5e79af418cc086b884fe7401112f0cf67b7033a"

      def install
        bin.install "gradleconf"
      end
    end
    on_arm do
      url "https://github.com/jksolbakken/gradleconf/releases/download/1.20260331025518/gradleconf_1.20260331025518_darwin_arm64.tar.gz"
      sha256 "961e75f48e5b9fa2a19708440df7b9ba74921336cd14312ca5094db6b4791b44"

      def install
        bin.install "gradleconf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jksolbakken/gradleconf/releases/download/1.20260331025518/gradleconf_1.20260331025518_linux_amd64.tar.gz"
        sha256 "6b2b5855d572ec5549dbdaa471c139bfd94cc6f9a511c8feb8218810eed6c984"

        def install
          bin.install "gradleconf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jksolbakken/gradleconf/releases/download/1.20260331025518/gradleconf_1.20260331025518_linux_arm64.tar.gz"
        sha256 "947e806bf7512e7fc4be8d7f248e98179dca75fc478d9354ec6997c93029f059"

        def install
          bin.install "gradleconf"
        end
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/gradleconf version")
  end
end
