# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gradleconf < Formula
  desc "Opinionated tool for configuring single module Kotlin Gradle projects"
  homepage "https://github.com/jksolbakken/gradleconf"
  version "1.20251231100231"

  on_macos do
    on_intel do
      url "https://github.com/jksolbakken/gradleconf/releases/download/1.20251231100231/gradleconf_1.20251231100231_darwin_amd64.tar.gz"
      sha256 "7d6a898e4585ff647699313bf8c7555bc7b54d32a9b9dc146ebfcbdf9a7ed5b1"

      def install
        bin.install "gradleconf"
      end
    end
    on_arm do
      url "https://github.com/jksolbakken/gradleconf/releases/download/1.20251231100231/gradleconf_1.20251231100231_darwin_arm64.tar.gz"
      sha256 "a1109a820104a7130a6b2370d8284c1d769682b43865e0585c060b5e1c80c710"

      def install
        bin.install "gradleconf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jksolbakken/gradleconf/releases/download/1.20251231100231/gradleconf_1.20251231100231_linux_amd64.tar.gz"
        sha256 "85b5def7cfbf950a5bf7b36adf2fdcb07dbb63377fa7d76b920c2c9a8014548d"

        def install
          bin.install "gradleconf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jksolbakken/gradleconf/releases/download/1.20251231100231/gradleconf_1.20251231100231_linux_arm64.tar.gz"
        sha256 "637cdcd2d8d6967844f31a16e396fae91aeccf0ea43cbda48702cc2adf44cb36"

        def install
          bin.install "gradleconf"
        end
      end
    end
  end

  test do
    assert_match version, shell_output("#{bin}/gradleconf version")
  end
end
